version: '3.8'

services:
  deepwiki:
    build: .
    ports:
      - "9781:9781"  # API port
      - "9782:9782"  # Next.js port (Host:Container)
    env_file:
      - .env
    environment:
      - PORT=9781  # Internal API port
      - NEXT_PUBLIC_PORT=9782  # External Next.js port (for client-side code)
      - NODE_ENV=production
      - SERVER_BASE_URL=http://localhost:9781  # Internal API URL for container
    volumes:
      - ~/.adalflow:/root/.adalflow  # Persist repository and embedding data
    networks:
      - deepwiki_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9781/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  deepwiki_mcp:
    build:
      context: .
      dockerfile: deepwiki_mcp/Dockerfile
    ports:
      - "9783:9783"  # External:Internal MCP port
    env_file:
      - .env
    environment:
      - MCP_PORT=9783  # Internal MCP port
      - DEEPWIKI_API_HOST=http://deepwiki:9781  # Internal container communication
      - PYTHONUNBUFFERED=1
    depends_on:
      deepwiki:
        condition: service_healthy
    networks:
      - deepwiki_network
    restart: unless-stopped

networks:
  deepwiki_network:
    driver: bridge
